### ISSUE TITLE
Undefined array key "hashtags" error whilst using ` | urlify` filter on tweet text

### ISSUE THREAD

**Issue by andrewhawkes** [percipioglobal/craft-tweet-feed#10]
This error gets thrown when a tweet doesn't have any hastags. The error seems to occur on this line:
`foreach($this->_unique_array($tweet['entities']['hashtags'], 'tag') as $hashtags) {`

It potentially just needs an additional check to ensure the hastags array is defined prior to this running?

The new filter was added in [4.1.0](https://github.com/percipioglobal/craft-tweet-feed/releases/tag/4.1.0)  after my FR https://github.com/percipioglobal/craft-tweet-feed/issues/7

**Comment by cookie10codes** [comment]
Hi @andrewhawkes,

Can you show me where you are using the `| urlify` filter on please?

**Comment by andrewhawkes** [comment]
Cutdown version without all the markup:
```twig
{% set tweets = craft.tweetfeed.tweets(6,'author_id,context_annotations','&exclude=retweets,replies&user.fields=id,profile_image_url,username') %}

{% if tweets and tweets | length %}

  {% for tweet in tweets %}

    <p>{{ tweet | urlify | raw }}</p>
    
  {% endfor %}

{% endif %}
```

**Comment by cookie10codes** [comment]
Thanks for the feedback, I'll add it to our list to solve 👍🏼

**Comment by cookie10codes** [comment]
Hi @andrewhawkes,

Can you check if the new release fix this issue for you? You can re-open the issue if this is not resolved
