### ISSUE TITLE
craft.tweetfeed.tweets(2) returning forbidden

### ISSUE THREAD

**Issue by harry2909** [percipioglobal/craft-tweet-feed#16]
Our tweets component has stopped working, I've seen the following message on our hosting platform. There doesn't seem to be any extra information regarding the response annoyingly.

`[error] application: Client error: `GET https://api.twitter.com/2/users/380821123/tweets?max_results=5&tweet.fields=entities` resulted in a `403 Forbidden` response:`

Nothing has changed via the developer portal app or the twitter account. I've checked and all the relevant keys are correct.

Dumping `{% set tweets = craft.tweetfeed.tweets(2) %}` returns an empty array

Any advice on debugging this would be appreciated!

**Update: I've just disabled the plugin for now as I imagine this is something to do with the recent twitter API changes**

**Comment by michtio** [comment]
@harry2909 sorry for the late answer. But this has to do with the recent twitter API changes and towards payment features.

We will most likely abandon this plugin - as it's simply not worth it anymore.
